name: CI

on: 
  push:
    tags:
    - 'v*'

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - uses: nuget/setup-nuget@v1
    - run: nuget restore $Env:GITHUB_WORKSPACE\.NET\Examples\ConsoleWindowsLinuxMac\ConsoleWindowsLinuxMac_VS2019.sln
    - name: Build Windows Desktop
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\.NET\Examples\WindowsDesktop\WindowsDesktop_VS2019.sln -p:Configuration=Release
        rm $Env:GITHUB_WORKSPACE\.NET\Examples\WindowsDesktop\obj -r -fo
    - name: Build Console example
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\.NET\Examples\ConsoleWindowsLinuxMac\ConsoleWindowsLinuxMac.csproj /p:DeployOnBuild=true /p:PublishProfile=win-x86 /p:Configuration=Release /p:OutDir=bin/win-x86
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\.NET\Examples\ConsoleWindowsLinuxMac\ConsoleWindowsLinuxMac.csproj /p:DeployOnBuild=true /p:PublishProfile=win-x64 /p:Configuration=Release /p:OutDir=bin/win-x64
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\.NET\Examples\ConsoleWindowsLinuxMac\ConsoleWindowsLinuxMac.csproj /p:DeployOnBuild=true /p:PublishProfile=win-arm /p:Configuration=Release /p:OutDir=bin/win-arm
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\.NET\Examples\ConsoleWindowsLinuxMac\ConsoleWindowsLinuxMac.csproj /p:DeployOnBuild=true /p:PublishProfile=osx-x64 /p:Configuration=Release /p:OutDir=bin/osx-64
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\.NET\Examples\ConsoleWindowsLinuxMac\ConsoleWindowsLinuxMac.csproj /p:DeployOnBuild=true /p:PublishProfile=linux-arm /p:Configuration=Release /p:OutDir=bin/linux-arm
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\.NET\Examples\ConsoleWindowsLinuxMac\ConsoleWindowsLinuxMac.csproj /p:DeployOnBuild=true /p:PublishProfile=linux-x64 /p:Configuration=Release /p:OutDir=bin/linux-x64
        rm $Env:GITHUB_WORKSPACE\.NET\Examples\ConsoleWindowsLinuxMac\obj -r -fo
    - name: zip libraries
      run: |
        cd "$Env:GITHUB_WORKSPACE\.NET\Libraries\"
        7z a -tzip -mx=9 $Env:GITHUB_WORKSPACE\YaskawaSDK.zip *
    - name: zip full .NET\Examples
      run: 7z a -tzip -mx=9 $Env:GITHUB_WORKSPACE\YaskawaSDK_Full.zip $Env:GITHUB_WORKSPACE\.NET\Examples $Env:GITHUB_WORKSPACE\.NET\Libraries
    - name: zip desktop example
      run: |
        cd "$Env:GITHUB_WORKSPACE\.NET\Examples\WindowsDesktop\bin\Release\"
        7z a -tzip -mx=9 $Env:GITHUB_WORKSPACE\YaskawaSDK_DesktopExample.zip *
    - name: zip win-x86
      run: |
        cd "$Env:GITHUB_WORKSPACE\.NET\Examples\ConsoleWindowsLinuxMac\bin\win-x86\"
        7z a -tzip -mx=9 $Env:GITHUB_WORKSPACE\YaskawaSDK_ConsoleExample_win-x86.zip *
    - name: zip win-x64
      run: |
        cd "$Env:GITHUB_WORKSPACE\.NET\Examples\ConsoleWindowsLinuxMac\bin\win-x64\"
        7z a -tzip -mx=9 $Env:GITHUB_WORKSPACE\YaskawaSDK_ConsoleExample_win-x64.zip *
    - name: zip win-arm
      run: |
        cd "$Env:GITHUB_WORKSPACE\.NET\Examples\ConsoleWindowsLinuxMac\bin\win-arm\"
        7z a -tzip -mx=9 $Env:GITHUB_WORKSPACE\YaskawaSDK_ConsoleExample_win-arm.zip *
    - name: zip osx-64
      run: |
        cd "$Env:GITHUB_WORKSPACE\.NET\Examples\ConsoleWindowsLinuxMac\bin\osx-64\"
        7z a -tzip -mx=9 $Env:GITHUB_WORKSPACE\YaskawaSDK_ConsoleExample_osx-64.zip *
    - name: zip linux-arm
      run: |
        cd "$Env:GITHUB_WORKSPACE\.NET\Examples\ConsoleWindowsLinuxMac\bin\linux-arm\"
        7z a -tzip -mx=9 $Env:GITHUB_WORKSPACE\YaskawaSDK_ConsoleExample_linux-arm.zip *
    - name: zip linux-x64
      run: |
        cd "$Env:GITHUB_WORKSPACE\.NET\Examples\ConsoleWindowsLinuxMac\bin\linux-x64\"
        7z a -tzip -mx=9 $Env:GITHUB_WORKSPACE\YaskawaSDK_ConsoleExample_linux-x64.zip *
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "YaskawaSDK_Full.zip,YaskawaSDK_ConsoleExample_win-x86.zip,YaskawaSDK_ConsoleExample_win-x64.zip,YaskawaSDK_ConsoleExample_win-arm.zip,YaskawaSDK_ConsoleExample_osx-64.zip,YaskawaSDK_ConsoleExample_linux-arm.zip,YaskawaSDK_ConsoleExample_linux-x64.zip,YaskawaSDK_LABView.zip,YaskawaSDK_Python.zip,YaskawaSDK_DesktopExample.zip,YaskawaSDK.zip"
        bodyFile: "whatsNew.md"
        token: ${{ secrets.GITHUB_TOKEN }}
